# Generated by Django 6.1.1 on 2026-09-28 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('head_of_department', models.CharField(max_length=120, verbose_name='Завідувач кафедри')),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва дисципліни')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Опис')),
                ('coordinator_name', models.CharField(max_length=120, verbose_name='Імʼя координатора набору')),
                ('coordinator_contact', models.CharField(max_length=120, verbose_name='Контакт координатора')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='faculty.department', verbose_name='Випускова кафедра')),
                ('disciplines', models.ManyToManyField(related_name='specialties', to='faculty.discipline', verbose_name='Список дисциплін')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Імʼя')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('degree', models.CharField(max_length=100, verbose_name='Ступінь')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='faculty.department', verbose_name='Кафедра')),
            ],
        ),
    ]
