# Generated by Django 6.1.1 on 2026-09-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Головна сторінка', max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст головної сторінки')),
            ],
            options={
                'verbose_name': 'Текст головної сторінки',
                'verbose_name_plural': 'Налаштування головної сторінки',
            },
        ),
        migrations.RemoveField(
            model_name='specialty',
            name='disciplines',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедри'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Спеціальність', 'verbose_name_plural': 'Спеціальності'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Викладач', 'verbose_name_plural': 'Викладачі'},
        ),
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(max_length=255, verbose_name='Завідувач кафедри'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='coordinator_contact',
            field=models.CharField(max_length=255, verbose_name='Контакт координатора набору'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='coordinator_name',
            field=models.CharField(max_length=255, verbose_name='Імʼя координатора набору'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(max_length=255, verbose_name='Ступінь'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Імʼя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Посада'),
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.AddField(
            model_name='specialty',
            name='disciplines',
            field=models.TextField(blank=True, default='', help_text='Введіть список дисциплін (наприклад, через кому або з нового рядка)', verbose_name='Список дисциплін'),
        ),
    ]
