# Generated by Django 6.1.1 on 2026-09-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_homepagecontent_remove_specialty_disciplines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Бакалаврат'), ('master', 'Магістратура'), ('phd', 'Аспірантура')], default='bachelor', max_length=20, verbose_name='Рівень вищої освіти'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код спеціальності'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='disciplines',
            field=models.TextField(blank=True, default='', verbose_name='Що вивчається / Чого навчишся'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва (Освітня програма)'),
        ),
    ]
