# Generated by Django 6.1.1 on 2026-10-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_specialty_degree_alter_specialty_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255, verbose_name='Університет')),
                ('languages', models.CharField(max_length=255, verbose_name='Мови навчання')),
                ('places', models.CharField(max_length=50, verbose_name='Кількість місць')),
                ('deadline', models.DateField(verbose_name='Дедлайн подачі')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Програма обміну',
                'verbose_name_plural': 'Програми обміну',
            },
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO faculty_exchangeprogram (university, languages, places, deadline, description)
                VALUES ('Uniwersytet Warszawski, Польща', 'польська, англійська', '5', '2026-11-15',
                        'Один з найкращих університетів Польщі з багатими академічними традиціями.'),
                       ('KU Leuven (Бельгія)', 'English', '2 місця', '2026-12-01',
                        'Найстаріший університет Бельгії, відомий своїми інноваційними дослідженнями.'),
                       ('Vilnius University, Литва', 'англійська', 'до 4', '2026-10-20',
                        'Провідний заклад вищої освіти Литви, розташований у мальовничому старому місті.'),
                       ('Uniwersytet Jagielloński, Польща', 'Польська, Англійська', '3', '2026-11-15',
                        'Найстаріший виш Польщі, що пропонує широкий вибір гуманітарних дисциплін.'),
                       ('University of Tartu - Естонія', 'англійська, естонська', '2', '2027-01-10',
                        'Головний університет Естонії, лідер у сфері цифрових та інновацій.'),
                       ('Masaryk University, Чехія', 'англійська', '1 місце', '2026-09-30',
                        'Динамічний університет у Брно з сучасним кампусом та розвиненою інфраструктурою.');
                """,
            reverse_sql="DELETE FROM faculty_exchangeprogram;"
        )
    ]
