# Generated by Django 6.1.1 on 2026-10-04 07:42

from django.db import migrations, models

def split_university(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        raw = program.university
        if '(' in raw and ')' in raw:
            program.country = raw[raw.find('(')+1 : raw.find(')')].strip()
            program.university = raw[:raw.find('(')].strip()
        elif ' - ' in raw:
            parts = raw.split(' - ')
            program.university = parts[0].strip()
            program.country = parts[1].strip()
        elif ',' in raw:
            parts = raw.split(',')
            program.university = parts[0].strip()
            program.country = parts[1].strip()
        program.save()

def merge_university(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        program.university = f"{program.university}, {program.country}"
        program.country = ""
        program.save()

class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_exchange_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprogram',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Країна'),
        ),
        migrations.RunPython(split_university, reverse_code=merge_university),
    ]
