# Generated by Django 6.1.1 on 2026-10-04 07:49

import re
from django.db import migrations, models

def clean_places(apps, schema_editor):
    ExchangeProgram = apps.get_model('faculty', 'ExchangeProgram')
    for program in ExchangeProgram.objects.all():
        match = re.search(r'\d+', str(program.places))
        if match:
            program.places = match.group(0)
        else:
            program.places = '0'
        program.save()

def reverse_clean_places(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_split_country'),
    ]

    operations = [
        migrations.RunPython(clean_places, reverse_code=reverse_clean_places),
        migrations.AlterField(
            model_name='exchangeprogram',
            name='places',
            field=models.IntegerField(verbose_name='Кількість місць'),
        ),
    ]
