# Generated by Django 6.1.1 on 2026-10-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_places_to_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='educ_program',
            field=models.CharField(default=None, max_length=50, verbose_name='Освітня програма'),
            preserve_default=False,
        ),
    ]
