# Generated by Django 6.1.1 on 2026-10-06 06:44

from django.db import migrations
# Generated by Django 6.1.1 on 2026-10-06 06:05

from django.db import migrations

def load_initial_data(apps, schema_editor):
    Department = apps.get_model('faculty', 'Department')
    Specialty = apps.get_model('faculty', 'Specialty')
    HomePageContent = apps.get_model('faculty', 'HomePageContent')

    # ================= 1. ГОЛОВНА СТОРІНКА =================
    home_text = """Факультет провадить навчання на трьох рівнях вищої освіти — бакалаврат, магістеріум та докторантура/аспірантура.

На бакалавраті здійснюються такі освітні програми: політологія, соціологія, міжнародні відносини, журналістика (звʼязки з громадськістю або PR).
Магістрів Факультет навчає за такими програмами: політологія («Європейські студії» й «Німецькі та Європейські студії»), соціологія, журналістика, зв’язки з громадськістю, міжнародні відносини, а останнім часом — ще й «Антикорупційні студії».

На ФСНСТ діють наукові структури:
Центр «Інститут громадянської освіти ім. С.Г. Рябова»;
Школа політичної аналітики.

Для студентів усіх факультетів НаУКМА пропонуються програми додаткової спеціалізації (minor) за напрямами: «Політологія» та «Соціологія», а також сертифікатні програми для бакалаврів та магістрів.

Факультет має значні матеріальні ресурси — спеціалізовані комп’ютерні класи, дві телестудії та фотостудію, студію «Молоде радіо». Важливою складовою розвитку є студентська активність (Могилянський портал «Бонет», радіо СМІТ, радіо К:)ВІТ)."""

    HomePageContent.objects.get_or_create(
        title="Факультет соціальних наук і соціальних технологій",
        defaults={"text": home_text}
    )

    dep_soc, _ = Department.objects.get_or_create(name="Кафедра соціології", defaults={"head_of_department": "Світлана Оксамитна"})
    dep_pol, _ = Department.objects.get_or_create(name="Кафедра політології", defaults={"head_of_department": "Олександр Дем'янчук"})
    dep_pr, _ = Department.objects.get_or_create(name="Кафедра зв’язків із громадськістю", defaults={"head_of_department": "Інформація оновлюється"})
    dep_jour, _ = Department.objects.get_or_create(name="Могилянська школа журналістики", defaults={"head_of_department": "Інформація оновлюється"})
    dep_ir, _ = Department.objects.get_or_create(name="Кафедра міжнародних відносин", defaults={"head_of_department": "Інформація оновлюється"})

    #БАКАЛАВРАТ
    Specialty.objects.get_or_create(
        name="Політологія", code="С2", educ_program = "Політологія",degree="bachelor", department=dep_pol,
        defaults={
            "coordinator_name": "Гнатюк Микола Миколайович", "coordinator_contact": "+38(073) 273 07 89, m.gnatiuk@ukma.edu.ua",
            "description": "У процесі навчання ти опановуєш ряд нормативних дисциплін, що формують базові знання і навички політолога. Водночас маєш можливість обирати професійно-орієнтовані і вибіркові дисципліни.\n\nЯкі міжнародні можливості?\nПід час навчання ти можеш отримати міжнародний академічний досвід (Friedrich Schiller University Jena, University of Toronto, University of Glasgow та ін.).\n\nДе ти зможеш працювати?\nУ науково-дослідних інститутах, банках, міжнародних компаніях, дипломатичній службі, медіа.",
            "disciplines": "• ґрунтовні теоретичні знання у галузі політології\n• успішне розв’язання конфліктів\n• політичний аналіз, прогноз\n• експертна оцінка подіям\n• професійна комунікація англійською"
        }
    )


    Specialty.objects.get_or_create(
        name="Соціологія", code="С5", educ_program = "Соціологія",degree="bachelor", department=dep_soc,
        defaults={
            "coordinator_name": "Прохорова Анна Андріївна", "coordinator_contact": "+38(067) 965 01 96, anna.prokhorova@ukma.edu.ua",
            "description": "Бути соціологом — означає бачити більше, ніж просто події довкола. Ти опануєш методи соціальних досліджень, аналізуватимеш сучасні суспільні виклики.\n\nМіжнародні можливості:\nНаУКМА співпрацює з університетами Торонто, Глазго, Тарту та іншими.\n\nДе ти зможеш працювати?\nУ дослідницьких центрах, бізнесі (маркетинг, PR), освіті, державному секторі та медіа.",
            "disciplines": "• сильна база з соціології\n• досвід власного дослідження\n• розуміння, як створюються стратегії\n• критичне мислення"
        }
    )

    Specialty.objects.get_or_create(
        name="Журналістика", code="С7", educ_program = "Зв’язки з громадськістю",degree="bachelor", department=dep_pr,
        defaults={
            "coordinator_name": "Коник Дмитро Леонідович", "coordinator_contact": "+38(067) 408 45 63, d.konyk@ukma.edu.ua",
            "description": "Освітня програма дасть тобі сучасні інструменти для ефективного управління комунікаціями. \n\nЧому ми?\nУнікальність програми полягає в чіткій спеціалізації — це єдина бакалаврська програма в Україні, що готує саме фахівців зі зв’язків з громадськістю.",
            "disciplines": "• управління комунікацією з аудиторіями\n• планування комунікаційних кампаній\n• управління репутацією компанії\n• створення контенту"
        }
    )

    #МАГІСТРАТУРА
    Specialty.objects.get_or_create(
        name="Політологія", code="С2", educ_program = "Антикорупційні студії",degree="master", department=dep_pol,
        defaults={
            "coordinator_name": "Чабанна Маргарита Валеріївна", "coordinator_contact": "+38(067) 509 22 43, chabanna@ukma.edu.ua",
            "description": "Спрямована на підготовку фахівців у сфері (анти)корупції, які володіють сучасним аналітичним і дослідницьким інструментарієм.\n\nДе працювати?\nФахівці з виявлення та запобігання корупції, експерти аналітичних центрів, комплаєнс-офіцери.",
            "disciplines": "• системний аналіз причин корупції\n• розробка антикорупційних інструментів\n• проведення експертизи\n• розслідування правопорушень"
        }
    )
    Specialty.objects.get_or_create(
        name="Політологія", code="С2", educ_program = "Політологія",degree="master", department=dep_pol,
        defaults={
            "coordinator_name": "Чабанна Маргарита Валеріївна", "coordinator_contact": "+38(067) 509 22 43, chabanna@ukma.edu.ua",
            "description": "Спрямована на підготовку фахівців у сфері (анти)корупції, які володіють сучасним аналітичним і дослідницьким інструментарієм.\n\nДе працювати?\nФахівці з виявлення та запобігання корупції, експерти аналітичних центрів, комплаєнс-офіцери.",
            "disciplines": "• системний аналіз причин корупції\n• розробка антикорупційних інструментів\n• проведення експертизи\n• розслідування правопорушень"
        }
    )

    Specialty.objects.get_or_create(
        name="Соціологія", code="С5", educ_program = "Соціологія",degree="master", department=dep_soc,
        defaults={
            "coordinator_name": "Прохорова Анна Андріївна", "coordinator_contact": "+38(067) 965 01 96, anna.prokhorova@ukma.edu.ua",
            "description": "Потужний акцент на практичних навичках і поглибленому викладанні кількісними, якісними та мішаними методами. Ми готуємо і до наукової кар’єри, і до аналітичної роботи в бізнесі.",
            "disciplines": "• аналітика для бізнесу та політик\n• проведення соціологічних досліджень\n• прийняття рішень на основі даних"
        }
    )

    Specialty.objects.get_or_create(
        name="Журналістика", code="С7", educ_program="Журналістика", degree="master", department=dep_jour,
        defaults={
            "coordinator_name": "Іванова Світлана Петрівна",
            "coordinator_contact": "+38(099) 305 28 20, S.ivanova@ukma.edu.ua",
            "description": "Могилянська школа журналістики — це унікальний освітній центр. Навчання побудоване на поєднанні теорії з практикою: студенти створюють власні медіапроєкти — від текстів до телевізійних сюжетів.",
            "disciplines": "• мультимедійні медіа\n• візуальні комунікації\n• протидія дезінформації"
        }
    )
    Specialty.objects.get_or_create(
        name="Журналістика", code="С7", educ_program="Зв’язки з громадськістю", degree="master", department=dep_jour,
        defaults={
            "coordinator_name": "Іванова Світлана Петрівна",
            "coordinator_contact": "+38(099) 305 28 20, S.ivanova@ukma.edu.ua",
            "description": "Могилянська школа журналістики — це унікальний освітній центр. Навчання побудоване на поєднанні теорії з практикою: студенти створюють власні медіапроєкти — від текстів до телевізійних сюжетів.",
            "disciplines": "• мультимедійні медіа\n• візуальні комунікації\n• протидія дезінформації"
        }
    )

    # АСПІРАНТУРА
    Specialty.objects.get_or_create(
        name="Соціологія", code="С5", educ_program="Соціологія", degree="phd", department=dep_soc,
        defaults={
            "coordinator_name": "Прохорова Анна Андріївна",
            "coordinator_contact": "+38(067) 965 01 96, anna.prokhorova@ukma.edu.ua",
            "description": "Докторська програма готує висококваліфікованих фахівців за найвищими світовими стандартами. Ми підтримуємо твою фахову активність.",
            "disciplines": "• вміння продукувати нові ідеї\n• проведення власного наукового дослідження\n• поєднання наукової й педагогічної діяльності"
        }
    )

    Specialty.objects.get_or_create(
        name="Журналістика", code="С7", educ_program="Медіа та комунікації", degree="phd", department=dep_jour,
        defaults={
            "coordinator_name": "Романюк Вікторія Сергіївна",
            "coordinator_contact": "+38(096) 287 38 48, victoria.romaniuk@ukma.edu.ua",
            "description": "Спрямована на формування системного наукового світогляду, розуміння засад академічної культури й етики. Форми навчання наближені до практичної наукової діяльності.",
            "disciplines": "• Сфера Досліджень\n• Сфера Комунікації\n• Сфера Менеджменту"
        }
    )


def unload_initial_data(apps, schema_editor):
    Department = apps.get_model('faculty', 'Department')
    HomePageContent = apps.get_model('faculty', 'HomePageContent')
    Department.objects.all().delete()
    HomePageContent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_specialty_educ_program'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_code=unload_initial_data),

    ]
